"""A fixed corpus of task -> expected routing, so a change to a trigger, a priority, or the
registry breaks an explicit test here rather than silently changing what gets routed where.

tests/fixtures/skill_routing_golden.json was generated by running the live engine
(classify_task + select_skills) against a curated set of tasks -- English and Spanish,
one positive and one near-miss negative per requires_trigger skill, and at least one
Figma-routed row -- and is a snapshot of that behavior, not a hand-derived spec. Update it
deliberately (regenerate and diff) when a routing change is intended; a failure here means
routing moved without anyone deciding it should.
"""
import json
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'ai_stack'))
import core  # noqa: E402
import skills  # noqa: E402

GOLDEN = json.loads((ROOT / 'tests/fixtures/skill_routing_golden.json').read_text())
PROFILES = ('fast', 'standard', 'strict')
REQUIRES_TRIGGER = {name for name, meta in skills.skill_registry().get('skills', {}).items()
                     if meta.get('requires_trigger')}


class GoldenCorpusShapeTests(unittest.TestCase):
    def test_at_least_forty_rows(self):
        self.assertGreaterEqual(len(GOLDEN), 40)

    def test_at_least_twenty_spanish_rows(self):
        es_words = {'el', 'la', 'de', 'que', 'para', 'con', 'del', 'las', 'los', 'una', 'un', 'en',
                    'al', 'este', 'nueva'}

        def is_spanish(task: str) -> bool:
            words = task.lower().replace(':', ' ').split()
            return sum(1 for w in words if w in es_words) >= 1 and any(
                w in task.lower() for w in ('ó', 'ñ', 'á', 'é', 'í', 'ú', 'arregla', 'migra', 'desglosa',
                                             'hoja de ruta', 'poc de', 'prueba de concepto', 'reescribe',
                                             'refactoriza', 'obsoleto', 'conflicto de', 'provisiona',
                                             'credenciales', 'cuestiona', 'actualiza', 'funcionalidad',
                                             'excepcion', 'bibliotecas', 'crashea'))
        spanish = [r['task'] for r in GOLDEN if is_spanish(r['task'])]
        self.assertGreaterEqual(len(spanish), 20, f'only found: {spanish}')

    def test_every_requires_trigger_skill_has_a_positive_row(self):
        seen = {name for row in GOLDEN for name in row['fast'] + row['standard'] + row['strict']}
        missing = REQUIRES_TRIGGER - seen
        self.assertFalse(missing, f'no golden row selects: {missing}')

    def test_every_requires_trigger_skill_has_a_near_miss_negative_row(self):
        # A "negative" row: same rough topic/type, but the specific trigger phrase absent,
        # so the skill correctly does not fire. We only require that at least one row in the
        # corpus exercises each trigger-gated skill's *absence* under a plausible-looking task.
        for name in REQUIRES_TRIGGER:
            negatives = [row for row in GOLDEN
                         if name not in row['fast'] + row['standard'] + row['strict']]
            self.assertGreater(len(negatives), 0, f'{name} has no negative row in the corpus')

    def test_at_least_one_figma_row(self):
        self.assertTrue(any(row.get('figma') for row in GOLDEN))


class GoldenRoutingTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix='skills-golden-')
        self.addCleanup(self.temp.cleanup)
        self.state = Path(self.temp.name)


def _make_row_test(row, profile):
    def test(self):
        task, figma = row['task'], row.get('figma')
        actual_type = core.classify_task(task, figma)
        self.assertEqual(actual_type, row['type'],
                          f'classify_task({task!r}, {figma!r}) drifted: expected {row["type"]!r}, got {actual_type!r}')
        actual = skills.select_skills(self.state, task, profile, figma)
        if actual != row[profile]:
            scores = skills.score_skills(self.state, task, figma)
            self.fail(f'{profile} routing drifted for {task!r}: expected {row[profile]!r}, got {actual!r}\n'
                      f'score_skills: {scores}')
    return test


for _i, _row in enumerate(GOLDEN):
    for _profile in PROFILES:
        _name = f'test_row_{_i:03d}_{_profile}'
        setattr(GoldenRoutingTests, _name, _make_row_test(_row, _profile))


if __name__ == '__main__':
    unittest.main()
